"use client";

import { useState, useRef, KeyboardEvent } from "react";
import type { AnalysisResult } from "@/lib/types";
import ScoreRing from "./ScoreRing";
import MetricBar from "./MetricBar";
import styles from "./ClarityApp.module.css";

const EXAMPLES = ["stripe.com", "notion.so", "linear.app", "vercel.com", "figma.com"];
const STEPS = [
  "Fetching page content",
  "Extracting visible text",
  "Scoring with Claude",
  "Writing suggestions",
];

type StepState = "" | "active" | "done";

function scoreGrade(s: number) {
  if (s >= 9) return "A+";
  if (s >= 8) return "A";
  if (s >= 7) return "B";
  if (s >= 6) return "C";
  if (s >= 4) return "D";
  return "F";
}

function scoreColorKey(s: number) {
  if (s >= 8) return "teal";
  if (s >= 6) return "amber";
  return "red";
}

function scoreVerdict(s: number) {
  if (s >= 9) return ["", "Exceptionally", " clear"];
  if (s >= 8) return ["Very ", "clear", " messaging"];
  if (s >= 7) return ["Mostly clear, ", "minor gaps", ""];
  if (s >= 6) return ["Moderate ", "clarity", ""];
  if (s >= 4) return ["Needs ", "significant", " work"];
  return ["", "Unclear", " messaging"];
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

function buildCopyText(result: AnalysisResult, hostname: string): string {
  const grade = scoreGrade(result.score);
  const lines = [
    `CLARITY REPORT — ${hostname}`,
    `Overall Score: ${result.score}/10 (${grade})`,
    ``,
    result.rationale,
    ``,
    `WHAT THIS BUSINESS DOES`,
    result.summary,
    ``,
    `DIMENSION SCORES`,
    ...result.metrics.map((m) => `  ${m.name}: ${m.score}/10 — ${m.note}`),
    ``,
    `HOW TO IMPROVE`,
    ...result.suggestions.map((s, i) => `  ${i + 1}. ${s}`),
    ``,
    `Generated by Clarity · Powered by Claude`,
  ];
  return lines.join("\n");
}

export default function ClarityApp() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [steps, setSteps] = useState<StepState[]>(["", "", "", ""]);
  const [loadingUrl, setLoadingUrl] = useState("");
  const [error, setError] = useState("");
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [hostname, setHostname] = useState("");
  const [copied, setCopied] = useState(false);
  const abortRef = useRef<AbortController | null>(null);

  function setStep(index: number, state: StepState) {
    setSteps((prev) => {
      const next = [...prev] as StepState[];
      next[index] = state;
      return next;
    });
  }

  async function runAnalysis() {
    const trimmed = url.trim();
    if (!trimmed) return;

    setError("");
    setResult(null);
    setHostname("");
    setLoading(true);
    setSteps(["", "", "", ""]);
    setCopied(false);

    const displayHost = trimmed.replace(/^https?:\/\//i, "").split("/")[0];
    setLoadingUrl(displayHost);

    setStep(0, "active");
    await sleep(500);
    setStep(0, "done");
    setStep(1, "active");
    await sleep(400);
    setStep(1, "done");
    setStep(2, "active");

    abortRef.current = new AbortController();

    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: trimmed }),
        signal: abortRef.current.signal,
      });

      setStep(2, "done");
      setStep(3, "active");

      const data = await res.json();
      if (!res.ok || data.error) throw new Error(data.error || "Analysis failed.");

      await sleep(300);
      setStep(3, "done");
      await sleep(200);

      setResult(data.result);
      setHostname(data.hostname);
    } catch (err) {
      if ((err as Error).name !== "AbortError") {
        setError((err as Error).message || "Something went wrong.");
      }
    } finally {
      setLoading(false);
    }
  }

  async function copyReport() {
    if (!result) return;
    await navigator.clipboard.writeText(buildCopyText(result, hostname));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleKey(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") runAnalysis();
  }

  const grade = result ? scoreGrade(result.score) : "";
  const colorKey = result ? scoreColorKey(result.score) : "teal";
  const [vBefore, vItalic, vAfter] = result ? scoreVerdict(result.score) : ["", "", ""];

  return (
    <>
      <header className={styles.header}>
        <div className={styles.logo}>
          <div className={styles.logoDot} />
          CLARITY
        </div>
        <div className={styles.headerRight}>
          <div className={styles.claudeBadge}>Powered by Claude</div>
        </div>
      </header>

      <main className={styles.main}>
        {/* Hero */}
        <section className={styles.hero}>
          <div className={styles.eyebrow}>Website Messaging Analyzer</div>
          <h1 className={styles.h1}>
            Does your site say<br />
            <em>what it actually does?</em>
          </h1>
          <p className={styles.heroSub}>
            Paste any URL. Claude scores your homepage copy across five dimensions
            and tells you exactly what to fix — no guessing, no generic advice.
          </p>
        </section>

        {/* Input */}
        <div className={styles.inputWrap}>
          <div className={styles.inputRow}>
            <input
              className={styles.urlInput}
              type="url"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              onKeyDown={handleKey}
              placeholder="https://yoursite.com"
              autoComplete="off"
              spellCheck={false}
            />
            <button className={styles.analyzeBtn} onClick={runAnalysis} disabled={loading}>
              {loading ? "Analyzing…" : "Analyze →"}
            </button>
          </div>
        </div>

        {/* Chips */}
        <div className={styles.chipsRow}>
          <span className={styles.chipLabel}>Try:</span>
          {EXAMPLES.map((ex) => (
            <button key={ex} className={styles.chip} onClick={() => setUrl("https://" + ex)}>
              {ex}
            </button>
          ))}
        </div>

        {/* Error */}
        {error && <div className={styles.error}>{error}</div>}

        {/* Loading */}
        {loading && (
          <div className={styles.loading}>
            <div className={styles.loadingUrl}>Analyzing {loadingUrl}</div>
            <div className={styles.scanWrap} />
            <div className={styles.steps}>
              {STEPS.map((label, i) => (
                <div
                  key={i}
                  className={`${styles.step} ${steps[i] === "active" ? styles.stepActive : ""} ${steps[i] === "done" ? styles.stepDone : ""}`}
                >
                  <div className={styles.stepDot} />
                  {label}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Result */}
        {result && !loading && (
          <div className={styles.result}>

            {/* ── Top row: score + metrics ── */}
            <div className={styles.topGrid}>

              {/* Score panel */}
              <div className={styles.scorePanel}>
                <div className={styles.scoreTop}>
                  <ScoreRing score={result.score} />
                  <div className={styles.scoreRight}>
                    <div className={styles.gradeWrap}>
                      <span className={`${styles.grade} ${styles[colorKey]}`}>{grade}</span>
                    </div>
                    <div className={styles.scoreNumber}>
                      {result.score}<span>/10</span>
                    </div>
                    <div className={styles.scoreVerdict}>
                      {vBefore}<em>{vItalic}</em>{vAfter}
                    </div>
                  </div>
                </div>
                <div className={`${styles.scoreBadge} ${styles[colorKey]}`}>
                  {colorKey === "teal" ? "● Clear" : colorKey === "amber" ? "◐ Adequate" : "○ Needs work"}
                </div>
                <p className={styles.scoreRationale}>{result.rationale}</p>
              </div>

              {/* Metrics panel */}
              <div className={styles.metricsPanel}>
                <div className={styles.metricsPanelLabel}>Dimension Breakdown</div>
                <div className={styles.metricsList}>
                  {result.metrics.map((m) => (
                    <MetricBar key={m.name} name={m.name} score={m.score} note={m.note} />
                  ))}
                </div>
              </div>
            </div>

            {/* ── Summary ── */}
            <div className={styles.divider}>
              <div className={styles.dividerLabel}>What this business does</div>
              <div className={styles.dividerLine} />
            </div>
            <div className={styles.summaryCard}>
              <div className={styles.summaryIcon}>◈</div>
              <p className={styles.summaryText}>{result.summary}</p>
            </div>

            {/* ── Suggestions ── */}
            <div className={styles.divider}>
              <div className={styles.dividerLabel}>How to improve</div>
              <div className={styles.dividerLine} />
              <button className={styles.copyBtn} onClick={copyReport}>
                {copied ? "Copied ✓" : "Copy report"}
              </button>
            </div>
            <div className={styles.suggestionsGrid}>
              {result.suggestions.slice(0, 3).map((s, i) => (
                <div key={i} className={styles.suggestionCard}>
                  <div className={styles.suggestionNum}>{String(i + 1).padStart(2, "0")}</div>
                  <div className={styles.suggestionText}>{s}</div>
                </div>
              ))}
            </div>

          </div>
        )}
      </main>

      {result && !loading && (
        <footer className={styles.footer}>
          <span>clarity — website messaging analyzer</span>
          <span>{hostname}</span>
        </footer>
      )}
    </>
  );
}
